# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Task1GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtGui
from PyQt5.QtWidgets import QApplication,QWidget, QVBoxLayout, QPushButton, QFileDialog , QLabel, QTextEdit
import sys
from PyQt5.QtGui import QPixmap
from pyqtgraph import PlotWidget
import pyqtgraph
from pyqtgraph import *
import pyqtgraph as pg
from pyqtgraph import PlotWidget, PlotItem



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.imageAndHistogramWidget = QtWidgets.QWidget(self.widget)
        self.imageAndHistogramWidget.setObjectName("imageAndHistogramWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.imageAndHistogramWidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.loadedImageLabel = QtWidgets.QLabel(self.imageAndHistogramWidget)
        self.loadedImageLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Old English Text MT")
        font.setPointSize(15)
        self.loadedImageLabel.setFont(font)
        self.loadedImageLabel.setObjectName("loadedImageLabel")
        self.horizontalLayout_6.addWidget(self.loadedImageLabel)
        self.histogramLabel = QtWidgets.QLabel(self.imageAndHistogramWidget)
        self.histogramLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Old English Text MT")
        font.setPointSize(14)
        self.histogramLabel.setFont(font)
        self.histogramLabel.setObjectName("histogramLabel")
        self.horizontalLayout_6.addWidget(self.histogramLabel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ImageWidget = QLabel(self.imageAndHistogramWidget)
        self.ImageWidget.setObjectName("ImageWidget")
        self.ImageWidget.setMaximumWidth(644)
        self.ImageWidget.setMaximumHeight(600)
        self.horizontalLayout_2.addWidget(self.ImageWidget)
        self.line = QtWidgets.QFrame(self.imageAndHistogramWidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.HistogramWidget = QtWidgets.QWidget(self.imageAndHistogramWidget)
        self.HistogramWidget.setObjectName("HistogramWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.HistogramWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2.addWidget(self.HistogramWidget)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.imageAndHistogramWidget)
        self.line_3 = QtWidgets.QFrame(self.widget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.filtersWigdet = QtWidgets.QWidget(self.widget)
        self.filtersWigdet.setObjectName("filtersWigdet")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.filtersWigdet)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.filterTLabel = QtWidgets.QLabel(self.filtersWigdet)
        self.filterTLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Old English Text MT")
        font.setPointSize(14)
        self.filterTLabel.setFont(font)
        self.filterTLabel.setObjectName("filterTLabel")
        self.horizontalLayout_5.addWidget(self.filterTLabel)
        self.filterFLabel = QtWidgets.QLabel(self.filtersWigdet)
        self.filterFLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Old English Text MT")
        font.setPointSize(14)
        self.filterFLabel.setFont(font)
        self.filterFLabel.setObjectName("filterFLabel")
        self.horizontalLayout_5.addWidget(self.filterFLabel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.filterInTDomainWidget = QtWidgets.QWidget(self.filtersWigdet)
        self.filterInTDomainWidget.setObjectName("filterInTDomainWidget")
        self.horizontalLayout_3.addWidget(self.filterInTDomainWidget)
        self.line_2 = QtWidgets.QFrame(self.filtersWigdet)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_3.addWidget(self.line_2)
        self.FilterInFDomainWidget = QtWidgets.QWidget(self.filtersWigdet)
        self.FilterInFDomainWidget.setObjectName("FilterInFDomainWidget")
        self.horizontalLayout_3.addWidget(self.FilterInFDomainWidget)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.filtersWigdet)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.horizontalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        self.menuSave_Image = QtWidgets.QMenu(self.menuOptions)
        self.menuSave_Image.setObjectName("menuSave_Image")
        self.menuFilters = QtWidgets.QMenu(self.menuOptions)
        self.menuFilters.setObjectName("menuFilters")
        self.menuDomain = QtWidgets.QMenu(self.menuOptions)
        self.menuDomain.setObjectName("menuDomain")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionBrowse_an_image = QtWidgets.QAction(MainWindow)
        self.actionBrowse_an_image.setObjectName("actionBrowse_an_image")
        self.actionFrom_ch_1 = QtWidgets.QAction(MainWindow)
        self.actionFrom_ch_1.setObjectName("actionFrom_ch_1")
        self.actionFrom_ch_2 = QtWidgets.QAction(MainWindow)
        self.actionFrom_ch_2.setObjectName("actionFrom_ch_2")
        self.actionFrom_ch_3 = QtWidgets.QAction(MainWindow)
        self.actionFrom_ch_3.setObjectName("actionFrom_ch_3")
        self.actionFrom_ch_4 = QtWidgets.QAction(MainWindow)
        self.actionFrom_ch_4.setObjectName("actionFrom_ch_4")
        self.actionLow_pass = QtWidgets.QAction(MainWindow)
        self.actionLow_pass.setObjectName("actionLow_pass")
        self.actionMedium_pass = QtWidgets.QAction(MainWindow)
        self.actionMedium_pass.setObjectName("actionMedium_pass")
        self.actionHigh_pass = QtWidgets.QAction(MainWindow)
        self.actionHigh_pass.setObjectName("actionHigh_pass")
        self.actionLa_placian = QtWidgets.QAction(MainWindow)
        self.actionLa_placian.setObjectName("actionLa_placian")
        self.actionCh_1 = QtWidgets.QAction(MainWindow)
        self.actionCh_1.setObjectName("actionCh_1")
        self.actionCh_2 = QtWidgets.QAction(MainWindow)
        self.actionCh_2.setObjectName("actionCh_2")
        self.actionCh_3 = QtWidgets.QAction(MainWindow)
        self.actionCh_3.setObjectName("actionCh_3")
        self.actionCh_4 = QtWidgets.QAction(MainWindow)
        self.actionCh_4.setObjectName("actionCh_4")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionHistogram = QtWidgets.QAction(MainWindow)
        self.actionHistogram.setObjectName("actionHistogram")
        self.actionSpatial_Domain = QtWidgets.QAction(MainWindow)
        self.actionSpatial_Domain.setObjectName("actionSpatial_Domain")
        self.actionFrequency_Domain = QtWidgets.QAction(MainWindow)
        self.actionFrequency_Domain.setObjectName("actionFrequency_Domain")
        self.actionSave_Histogram = QtWidgets.QAction(MainWindow)
        self.actionSave_Histogram.setObjectName("actionSave_Histogram")
        self.actionFreq_filtered = QtWidgets.QAction(MainWindow)
        self.actionFreq_filtered.setObjectName("actionFreq_filtered")
        self.menuFile.addAction(self.actionBrowse_an_image)
        self.menuFile.addAction(self.actionExit)
        self.menuSave_Image.addAction(self.actionFrom_ch_1)
        self.menuSave_Image.addAction(self.actionFrom_ch_2)
        self.menuSave_Image.addAction(self.actionFreq_filtered)
        self.menuFilters.addAction(self.actionLow_pass)
        self.menuFilters.addAction(self.actionMedium_pass)
        self.menuFilters.addAction(self.actionHigh_pass)
        self.menuFilters.addAction(self.actionLa_placian)
        self.menuDomain.addAction(self.actionSpatial_Domain)
        self.menuDomain.addAction(self.actionFrequency_Domain)
        self.menuOptions.addAction(self.menuDomain.menuAction())
        self.menuOptions.addAction(self.menuFilters.menuAction())
        self.menuOptions.addSeparator()
        self.menuOptions.addAction(self.actionHistogram)
        self.menuOptions.addSeparator()
        self.menuOptions.addAction(self.menuSave_Image.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.loadedImageLabel.setText(_translate("MainWindow", "Loaded Image"))
        self.histogramLabel.setText(_translate("MainWindow", "Histogram"))
        self.filterTLabel.setText(_translate("MainWindow", "Filter in Spatial domain"))
        self.filterFLabel.setText(_translate("MainWindow", "Filter in Frequency domain"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuOptions.setTitle(_translate("MainWindow", "Options"))
        self.menuSave_Image.setTitle(_translate("MainWindow", "Save Image"))
        self.menuFilters.setTitle(_translate("MainWindow", "Filters"))
        self.menuDomain.setTitle(_translate("MainWindow", "Domain"))
        self.actionBrowse_an_image.setText(_translate("MainWindow", "Browse an image"))
        self.actionBrowse_an_image.setShortcut(_translate("MainWindow", "Shift+O"))
        self.actionFrom_ch_1.setText(_translate("MainWindow", "Histogram"))
        self.actionFrom_ch_2.setText(_translate("MainWindow", "Spatial filtered"))
        self.actionFrom_ch_3.setText(_translate("MainWindow", "From ch 3"))
        self.actionFrom_ch_4.setText(_translate("MainWindow", "From ch 4"))
        self.actionLow_pass.setText(_translate("MainWindow", "Low pass"))
        self.actionLow_pass.setShortcut(_translate("MainWindow", "L"))
        self.actionMedium_pass.setText(_translate("MainWindow", "Medium pass"))
        self.actionMedium_pass.setShortcut(_translate("MainWindow", "M"))
        self.actionHigh_pass.setText(_translate("MainWindow", "High pass"))
        self.actionHigh_pass.setShortcut(_translate("MainWindow", "H"))
        self.actionLa_placian.setText(_translate("MainWindow", "La placian"))
        self.actionLa_placian.setShortcut(_translate("MainWindow", "A"))
        self.actionCh_1.setText(_translate("MainWindow", "Ch 1"))
        self.actionCh_1.setShortcut(_translate("MainWindow", "1"))
        self.actionCh_2.setText(_translate("MainWindow", "Ch 2"))
        self.actionCh_2.setShortcut(_translate("MainWindow", "2"))
        self.actionCh_3.setText(_translate("MainWindow", "Ch 3"))
        self.actionCh_3.setShortcut(_translate("MainWindow", "3"))
        self.actionCh_4.setText(_translate("MainWindow", "Ch 4"))
        self.actionCh_4.setShortcut(_translate("MainWindow", "4"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Esc"))
        self.actionHistogram.setText(_translate("MainWindow", "Histogram"))
        self.actionSpatial_Domain.setText(_translate("MainWindow", "Spatial Domain"))
        self.actionFrequency_Domain.setText(_translate("MainWindow", "Frequency Domain"))
        self.actionSave_Histogram.setText(_translate("MainWindow", "Save Histogram"))
        self.actionFreq_filtered.setText(_translate("MainWindow", "Freq filtered"))


        #Adding actions to menu items or buttons if there are any
        self.actionExit.triggered.connect(lambda: self.exit() )
        self.actionBrowse_an_image.triggered.connect(lambda: self.browseAnImg())
        self.actionSpatial_Domain.triggered.connect(lambda: self.setDomain("S"))
        self.actionFrequency_Domain.triggered.connect(lambda: self.setDomain("F"))
        self.actionLow_pass.triggered.connect(lambda: self.filterSelection("LO"))
        self.actionHigh_pass.triggered.connect(lambda: self.filterSelection("HI"))
        self.actionMedium_pass.triggered.connect(lambda: self.filterSelection("MED"))
        self.actionLa_placian.triggered.connect(lambda: self.filterSelection("PLA"))
        self.actionHistogram.triggered.connect(lambda: self.histogramRun())
        self.actionSave_Histogram.triggered.connect(lambda : self.saveImag("Histogram"))
        self.actionFreq_filtered.triggered.connect(lambda : self.saveImag("FreqFilter"))
        self.actionFrom_ch_2.triggered.connect(lambda : self.saveImag("SpatialFilter"))

        #Declaration of any global variables 
        self.logHistory=[] #A list created in order to log every action on the gui from its start till its closed by the user 
        self.ImageXsize=364
        
    #Start of functions 
    #Save image function
    def saveImag(self, whichScreenText):
        self.logging("The save image function was called")
        if whichScreenText=="Histogram":
            self.logging("The GUI is now saving the histogram as a png image")
            img=pyqtgraph.exporters.ImageExporter(self.HistogramWidget.scene())
            img.export('The_Histogram.png') 
        elif whichScreenText=="FreqFilter":
            self.logging("The GUI is now saving the Image from the frequency domian as a png image")
            img=pyqtgraph.exporters.ImageExporter(self.FilterInFDomainWidget.scene())
            img.export('The_Image_from_the_freq_domain.png') 
        else:
            self.logging("The GUI is now saving the image from the spatial domain as a png image")
            img=pyqtgraph.exporters.ImageExporter(self.filterInTDomainWidget.scene())
            img.export('The_Image_from_the_spatial_domain.png') 

    #Histogram implementation function
    def histogramRun(self):
        pass
    #Selection of filter function 
    def filterSelection(self, filterTypeText):
        pass
    #Selecting the domain each time a filter is chosen to allow for different domain selection each time
    def setDomain(self, domianIdentifierChar):
        pass
    #The browse image function 
    def browseAnImg(self):
        self.logging("browseAnImg function was called")
        image=QFileDialog.getOpenFileName()
        self.logging("Image path was chosen from the dialog box")
        imagePath = image[0]
        self.logging("image path is set to "+imagePath)
        pixmap = QPixmap(imagePath)
        #self.ImageWidget.resize(self.ImageXsize, self.ImageYsize)
        #self.ImageWidget.adjustSize()

        self.ImageWidget.setPixmap(QPixmap(pixmap).scaledToWidth(self.ImageXsize))
        self.ImageWidget.setScaledContents(True)
        print(self.ImageXsize)
        print(pixmap.size())
        self.ImageWidget.show()

    #The Exit function 
    def exit(self):
        self.logging("Exit function was called")
        sys.exit()
        
    #The logging function 
    def logging(self, text):
        f=open("Task1CVLog.txt","w+")
        self.logHistory.append(text)
        for i in self.logHistory:
            f.write("=> %s\r\n" %(i))
        f.close()



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
