# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(826, 544)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # Root layout
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout.setSpacing(6)

        # Outer widget
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")

        # Main vertical layout — holds all 3 rows
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout.setSpacing(6)

        # ── ROW 1: Loaded Image + Histogram ──────────────────────────────────
        self.imageAndHistogramWidget = QtWidgets.QWidget(self.widget)
        self.imageAndHistogramWidget.setObjectName("imageAndHistogramWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.imageAndHistogramWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")

        # Row 1 header labels
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")

        self.loadedImageLabel = QtWidgets.QLabel(self.imageAndHistogramWidget)
        # FIX: removed fixed max height so label scales with font/window
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(True)
        self.loadedImageLabel.setFont(font)
        self.loadedImageLabel.setObjectName("loadedImageLabel")
        # FIX: stretch so each label takes equal width
        self.horizontalLayout_6.addWidget(self.loadedImageLabel, 1)

        self.histogramLabel = QtWidgets.QLabel(self.imageAndHistogramWidget)
        font2 = QtGui.QFont()
        font2.setFamily("Times New Roman")
        font2.setPointSize(11)
        font2.setBold(True)
        self.histogramLabel.setFont(font2)
        self.histogramLabel.setObjectName("histogramLabel")
        self.horizontalLayout_6.addWidget(self.histogramLabel, 1)

        self.verticalLayout_3.addLayout(self.horizontalLayout_6)

        # Row 1 canvases
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        self.LoadedImageWidget = QtWidgets.QWidget(self.imageAndHistogramWidget)
        self.LoadedImageWidget.setObjectName("LoadedImageWidget")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.LoadedImageWidget)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_9.addLayout(self.verticalLayout_5)
        self.horizontalLayout_2.addWidget(self.LoadedImageWidget, 1)

        self.line = QtWidgets.QFrame(self.imageAndHistogramWidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)

        self.OriginalHistogramWidget = QtWidgets.QWidget(self.imageAndHistogramWidget)
        self.OriginalHistogramWidget.setObjectName("OriginalHistogramWidget")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.OriginalHistogramWidget)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_10.addLayout(self.verticalLayout_6)
        self.horizontalLayout_2.addWidget(self.OriginalHistogramWidget, 1)

        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        # FIX: give row 1 a stretch factor so rows share space proportionally
        self.verticalLayout.addWidget(self.imageAndHistogramWidget, 1)

        # ── ROW 2: Image from equalized histogram + Equalized histogram ───────
        self.equalizedHistogramWidget = QtWidgets.QWidget(self.widget)
        self.equalizedHistogramWidget.setObjectName("equalizedHistogramWidget")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.equalizedHistogramWidget)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")

        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")

        # Row 2 header labels
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")

        self.reversedImage = QtWidgets.QLabel(self.equalizedHistogramWidget)
        font3 = QtGui.QFont()
        font3.setFamily("Times New Roman")
        font3.setPointSize(11)
        font3.setBold(True)
        self.reversedImage.setFont(font3)
        self.reversedImage.setWordWrap(True)
        self.reversedImage.setObjectName("reversedImage")
        self.horizontalLayout_8.addWidget(self.reversedImage, 1)

        self.histogramLabel_2 = QtWidgets.QLabel(self.equalizedHistogramWidget)
        font4 = QtGui.QFont()
        font4.setFamily("Times New Roman")
        font4.setPointSize(11)
        font4.setBold(True)
        self.histogramLabel_2.setFont(font4)
        self.histogramLabel_2.setObjectName("histogramLabel_2")
        self.horizontalLayout_8.addWidget(self.histogramLabel_2, 1)

        self.verticalLayout_4.addLayout(self.horizontalLayout_8)

        # Row 2 canvases
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")

        self.ImageFromEqualizedHistogramWidget = QtWidgets.QWidget(self.equalizedHistogramWidget)
        self.ImageFromEqualizedHistogramWidget.setObjectName("ImageFromEqualizedHistogramWidget")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.ImageFromEqualizedHistogramWidget)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_11.addLayout(self.verticalLayout_7)
        self.horizontalLayout_7.addWidget(self.ImageFromEqualizedHistogramWidget, 1)

        self.line_4 = QtWidgets.QFrame(self.equalizedHistogramWidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_7.addWidget(self.line_4)

        self.EqualizedHistogramWidget = QtWidgets.QWidget(self.equalizedHistogramWidget)
        self.EqualizedHistogramWidget.setObjectName("EqualizedHistogramWidget")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.EqualizedHistogramWidget)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_12.addLayout(self.verticalLayout_8)
        self.horizontalLayout_7.addWidget(self.EqualizedHistogramWidget, 1)

        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_15.addLayout(self.verticalLayout_4)
        self.verticalLayout.addWidget(self.equalizedHistogramWidget, 1)

        # ── ROW 3: Filters ────────────────────────────────────────────────────
        self.filtersWigdet = QtWidgets.QWidget(self.widget)
        self.filtersWigdet.setObjectName("filtersWigdet")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.filtersWigdet)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        self.line_3 = QtWidgets.QFrame(self.filtersWigdet)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)

        # Row 3 header labels
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")

        self.filterTLabel = QtWidgets.QLabel(self.filtersWigdet)
        font5 = QtGui.QFont()
        font5.setFamily("Times New Roman")
        font5.setPointSize(11)
        font5.setBold(True)
        self.filterTLabel.setFont(font5)
        self.filterTLabel.setObjectName("filterTLabel")
        self.horizontalLayout_5.addWidget(self.filterTLabel, 1)

        self.filterFLabel = QtWidgets.QLabel(self.filtersWigdet)
        font6 = QtGui.QFont()
        font6.setFamily("Times New Roman")
        font6.setPointSize(11)
        font6.setBold(True)
        self.filterFLabel.setFont(font6)
        self.filterFLabel.setObjectName("filterFLabel")
        self.horizontalLayout_5.addWidget(self.filterFLabel, 1)

        self.verticalLayout_2.addLayout(self.horizontalLayout_5)

        # Row 3 canvases
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")

        self.FilterInSpatialDomainWidget = QtWidgets.QWidget(self.filtersWigdet)
        self.FilterInSpatialDomainWidget.setObjectName("FilterInSpatialDomainWidget")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.FilterInSpatialDomainWidget)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_13.addLayout(self.verticalLayout_9)
        self.horizontalLayout_3.addWidget(self.FilterInSpatialDomainWidget, 1)

        self.line_2 = QtWidgets.QFrame(self.filtersWigdet)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_3.addWidget(self.line_2)

        self.FilterInFreqDomainWidget = QtWidgets.QWidget(self.filtersWigdet)
        self.FilterInFreqDomainWidget.setObjectName("FilterInFreqDomainWidget")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.FilterInFreqDomainWidget)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_14.addLayout(self.verticalLayout_10)
        self.horizontalLayout_3.addWidget(self.FilterInFreqDomainWidget, 1)

        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.filtersWigdet, 1)

        # Assemble
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.horizontalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)

        # Menu bar
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 826, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        self.menuFilters = QtWidgets.QMenu(self.menuOptions)
        self.menuFilters.setObjectName("menuFilters")
        self.menuDomain = QtWidgets.QMenu(self.menuOptions)
        self.menuDomain.setObjectName("menuDomain")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # Actions
        self.actionBrowse_an_image = QtWidgets.QAction(MainWindow)
        self.actionBrowse_an_image.setObjectName("actionBrowse_an_image")
        self.actionFrom_ch_1 = QtWidgets.QAction(MainWindow)
        self.actionFrom_ch_1.setObjectName("actionFrom_ch_1")
        self.actionFrom_ch_2 = QtWidgets.QAction(MainWindow)
        self.actionFrom_ch_2.setObjectName("actionFrom_ch_2")
        self.actionFrom_ch_3 = QtWidgets.QAction(MainWindow)
        self.actionFrom_ch_3.setObjectName("actionFrom_ch_3")
        self.actionFrom_ch_4 = QtWidgets.QAction(MainWindow)
        self.actionFrom_ch_4.setObjectName("actionFrom_ch_4")
        self.actionLow_pass = QtWidgets.QAction(MainWindow)
        self.actionLow_pass.setObjectName("actionLow_pass")
        self.actionMedium_pass = QtWidgets.QAction(MainWindow)
        self.actionMedium_pass.setObjectName("actionMedium_pass")
        self.actionHigh_pass = QtWidgets.QAction(MainWindow)
        self.actionHigh_pass.setObjectName("actionHigh_pass")
        self.actionLa_placian = QtWidgets.QAction(MainWindow)
        self.actionLa_placian.setObjectName("actionLa_placian")
        self.actionCh_1 = QtWidgets.QAction(MainWindow)
        self.actionCh_1.setObjectName("actionCh_1")
        self.actionCh_2 = QtWidgets.QAction(MainWindow)
        self.actionCh_2.setObjectName("actionCh_2")
        self.actionCh_3 = QtWidgets.QAction(MainWindow)
        self.actionCh_3.setObjectName("actionCh_3")
        self.actionCh_4 = QtWidgets.QAction(MainWindow)
        self.actionCh_4.setObjectName("actionCh_4")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSpatial_Domain = QtWidgets.QAction(MainWindow)
        self.actionSpatial_Domain.setObjectName("actionSpatial_Domain")
        self.actionFrequency_Domain = QtWidgets.QAction(MainWindow)
        self.actionFrequency_Domain.setObjectName("actionFrequency_Domain")
        self.actionSave_Histogram = QtWidgets.QAction(MainWindow)
        self.actionSave_Histogram.setObjectName("actionSave_Histogram")
        self.actionFreq_filtered = QtWidgets.QAction(MainWindow)
        self.actionFreq_filtered.setObjectName("actionFreq_filtered")
        self.actionHistogram_2 = QtWidgets.QAction(MainWindow)
        self.actionHistogram_2.setObjectName("actionHistogram_2")
        self.actionEqualized_histogram = QtWidgets.QAction(MainWindow)
        self.actionEqualized_histogram.setObjectName("actionEqualized_histogram")
        self.actionReturn_Image_from_equalized_histogram = QtWidgets.QAction(MainWindow)
        self.actionReturn_Image_from_equalized_histogram.setObjectName("actionReturn_Image_from_equalized_histogram")
        self.actionSave_equalized_histogram = QtWidgets.QAction(MainWindow)
        self.actionSave_equalized_histogram.setObjectName("actionSave_equalized_histogram")
        self.actionReversed_image_from_Eq_histo = QtWidgets.QAction(MainWindow)
        self.actionReversed_image_from_Eq_histo.setObjectName("actionReversed_image_from_Eq_histo")
        self.actionHistogram_Equalization = QtWidgets.QAction(MainWindow)
        self.actionHistogram_Equalization.setObjectName("actionHistogram_Equalization")

        self.menuFile.addAction(self.actionBrowse_an_image)
        self.menuFile.addAction(self.actionExit)
        self.menuFilters.addAction(self.actionLow_pass)
        self.menuFilters.addAction(self.actionMedium_pass)
        self.menuFilters.addAction(self.actionHigh_pass)
        self.menuFilters.addAction(self.actionLa_placian)
        self.menuDomain.addAction(self.actionSpatial_Domain)
        self.menuDomain.addAction(self.actionFrequency_Domain)
        self.menuOptions.addAction(self.menuDomain.menuAction())
        self.menuOptions.addAction(self.menuFilters.menuAction())
        self.menuOptions.addAction(self.actionHistogram_Equalization)
        self.menuOptions.addSeparator()
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Image Processing Studio"))
        self.loadedImageLabel.setText(_translate("MainWindow", "Loaded Image"))
        self.histogramLabel.setText(_translate("MainWindow", "Histogram"))
        self.reversedImage.setText(_translate("MainWindow", "Image from Equalized Histogram"))
        self.histogramLabel_2.setText(_translate("MainWindow", "Equalized Histogram"))
        self.filterTLabel.setText(_translate("MainWindow", "Filter in Spatial Domain"))
        self.filterFLabel.setText(_translate("MainWindow", "Filter in Frequency Domain"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuOptions.setTitle(_translate("MainWindow", "Options"))
        self.menuFilters.setTitle(_translate("MainWindow", "Filters"))
        self.menuDomain.setTitle(_translate("MainWindow", "Domain"))
        self.actionBrowse_an_image.setText(_translate("MainWindow", "Browse an image"))
        self.actionBrowse_an_image.setShortcut(_translate("MainWindow", "Shift+O"))
        self.actionFrom_ch_1.setText(_translate("MainWindow", "Histogram"))
        self.actionFrom_ch_2.setText(_translate("MainWindow", "Spatial filtered"))
        self.actionFrom_ch_3.setText(_translate("MainWindow", "From ch 3"))
        self.actionFrom_ch_4.setText(_translate("MainWindow", "From ch 4"))
        self.actionLow_pass.setText(_translate("MainWindow", "Low pass"))
        self.actionLow_pass.setShortcut(_translate("MainWindow", "L"))
        self.actionMedium_pass.setText(_translate("MainWindow", "Medium pass"))
        self.actionMedium_pass.setShortcut(_translate("MainWindow", "M"))
        self.actionHigh_pass.setText(_translate("MainWindow", "High pass"))
        self.actionHigh_pass.setShortcut(_translate("MainWindow", "H"))
        self.actionLa_placian.setText(_translate("MainWindow", "Laplacian"))
        self.actionLa_placian.setShortcut(_translate("MainWindow", "A"))
        self.actionCh_1.setText(_translate("MainWindow", "Ch 1"))
        self.actionCh_1.setShortcut(_translate("MainWindow", "1"))
        self.actionCh_2.setText(_translate("MainWindow", "Ch 2"))
        self.actionCh_2.setShortcut(_translate("MainWindow", "2"))
        self.actionCh_3.setText(_translate("MainWindow", "Ch 3"))
        self.actionCh_3.setShortcut(_translate("MainWindow", "3"))
        self.actionCh_4.setText(_translate("MainWindow", "Ch 4"))
        self.actionCh_4.setShortcut(_translate("MainWindow", "4"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Esc"))
        self.actionSpatial_Domain.setText(_translate("MainWindow", "Spatial Domain"))
        self.actionFrequency_Domain.setText(_translate("MainWindow", "Frequency Domain"))
        self.actionSave_Histogram.setText(_translate("MainWindow", "Save Histogram"))
        self.actionFreq_filtered.setText(_translate("MainWindow", "Freq filtered"))
        self.actionHistogram_2.setText(_translate("MainWindow", "Histogram"))
        self.actionEqualized_histogram.setText(_translate("MainWindow", "Equalized histogram"))
        self.actionReturn_Image_from_equalized_histogram.setText(_translate("MainWindow", "Return Image from equalized histogram"))
        self.actionSave_equalized_histogram.setText(_translate("MainWindow", "Equalized histogram"))
        self.actionReversed_image_from_Eq_histo.setText(_translate("MainWindow", "Reversed image from Eq. histo."))
        self.actionHistogram_Equalization.setText(_translate("MainWindow", "Histogram Equalization"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())